[mypy]
strict = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-deep_translator.*]
ignore_missing_imports = True

[mypy-slowapi.*]
ignore_missing_imports = True

[mypy-firecrawl_local.*]
ignore_missing_imports = True
