"""add scraped_name and is_bundle to sale_events

Revision ID: 4618dbf54f38
Revises: 9f41a20f9a7e
Create Date: 2026-05-13 07:55:50.998544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4618dbf54f38'
down_revision: Union[str, Sequence[str], None] = '9f41a20f9a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_events', sa.Column('scraped_name', sa.Text(), nullable=True))
    op.add_column('sale_events', sa.Column('is_bundle', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_events', 'is_bundle')
    op.drop_column('sale_events', 'scraped_name')
    # ### end Alembic commands ###
